stages:
  - deploy

send_github:
  stage: deploy
  only:
    - main
  script:
    # Send only last commit to github. Need is configured user and token.
    # - PUSH_SHA_GH=$(git rev-parse HEAD)
    # - git push github $PUSH_SHA_GH:main
    - if ! git remote -v | grep -q "github"; then
        git remote add github https://github.com/$USER_GITHUB/lab-to-hub.git ;
      fi
    - if ! git remote -v | grep -q "github.*$TOKEN_GITHUB"; then
        git remote set-url github https://$USER_GITHUB:$TOKEN_GITHUB@github.com/$USER_GITHUB/lab-to-hub.git ;
      fi
    - git branch --show-current
    - git checkout main
    - git push github main