name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
  
      - name: Install dependencies
        run: npm install
  
      - name: Build Angular project to production
        run: npm run build:prod
        
      #Create gh-pages branch to publish and deploy from dist/browser of main branch.
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: dist/browser/
